### ISSUE TITLE
First character of line truncated on shopping list

### ISSUE THREAD

**Issue by WhyMe4** [tmayoff/obsidian-meals#114]
Not sure if it's intentional, but if an ingredient line starts with the unit of measure and no space
1 medium yellow onion, diced

Then the list generated
- [ ] yellow onion, diced  medium 

So the UoM is removed.

**Comment by WhyMe4** [comment]
Correction, if the UoM is 2 characters, only the 1st character is removed.

**Comment by tmayoff** [comment]
I can't reproduce this (I'm getting other probably undesirable results) what version are you using?

**Comment by WhyMe4** [comment]
I’m think it was .1.1. I upgraded right before I posted. On Jul 9, 2024, at 4:22 PM, Tyler ***@***.***> wrote:﻿
I can't reproduce this (I'm getting other probably undesirable results) what version are you using, if not the latest can you upgrade?

**Comment by WhyMe4** [comment]
I confirmed 0.1.1
I've attached the recipe I was testing with.
[One Pot Black Bean Taco Spaghetti.md](https://github.com/user-attachments/files/16151146/One.Pot.Black.Bean.Taco.Spaghetti.md)

**Comment by tmayoff** [comment]
I see it now, I'll work on a fix

**Comment by tmayoff** [comment]
Okay so the problem is the lack of `-` at the beginning of the lines this plugin expects a list as the ingredients. I'll remove that requirement
