### ISSUE TITLE
Generate shopping list generates empty note

### ISSUE THREAD

**Issue by Netzahre** [tmayoff/obsidian-meals#29]
I cant seem to get a shopping list to generate anything else than an empty note, not sure if intentional and meant to be filled manually or an error. Tried changing the recipe format I had and even copy-paste the one specificed in a new empty not that I added to the meal plan with no luck

**Comment by tmayoff** [comment]
Could you paste the recipe and the Meal Plan note here, so I can try to reproduce it

**Comment by Netzahre** [comment]
I will link you the md files directly too in case I fuck up writing

Recipe

# [Chicken Alfredo](https://www.budgetbytes.com/chicken-alfredo/)

This Chicken Alfredo features pasta drenched in an ultra-rich and creamy sauce, topped with juicy strips of seared chicken.

![Chicken Alfredo](https://www.budgetbytes.com/wp-content/uploads/2022/07/Chicken-Alfredo-above.jpg)

# Ingredients
- 2  boneless, skinless chicken breasts (about 1.3 lb. total) ($6.49)
- 2 tsp Italian seasoning ($0.20)
- 1 Tbsp cooking oil ($0.04)
- 2 Tbsp butter ($0.22)
- 4 cloves garlic, minced ($0.32)
- 1 cup heavy cream ($1.25)
- 3/4 cup grated Parmesan ($1.08)
- 1/4 tsp salt ($0.02)
- 1/4 tsp pepper ($0.02)
- 1 Tbsp chopped parsley (optional garnish) ($0.10)
- 8 oz. fettuccine ($0.88)

### Instructions

- Season both sides of the chicken breast with Italian seasoning and a pinch of salt.
- Heat a large skillet over medium. Once hot, add the cooking oil and swirl to coat the surface. Add the chicken to the skillet and cook for about 7-8 minutes on each side, or until browned on the outside and cooked through.
- Remove the chicken to a clean plate and turn the heat under the skillet down to medium-low.
- Add the butter and minced garlic to the skillet. Stir and cook the garlic in the melted butter for about two minutes, dissolving the browned bits from the bottom of the skillet as you stir.
- Add the heavy cream and whisk to combine, dissolving any remaining browned bits. Allow the cream to come up to a simmer.
- While waiting for the cream to simmer, bring a pot of water to a boil for the fettuccine. Once boiling, add the pasta and continue to boil until tender (about 7 minutes). Reserve about ½ cup of the starchy cooking water just before draining the pasta.
- Once the cream is simmering, add the grated Parmesan to the skillet. Continue to whisk and stir until the Parmesan has melted into the sauce and the sauce has begun to simmer. Simmer the sauce for a few minutes, or until it becomes slightly thicker. Add salt and pepper to the sauce to taste.
- Add the drained pasta to the skillet with the creamy sauce and toss to combine. If the sauce becomes too thick, add a couple of tablespoons of the reserved pasta water and toss to combine with the sauce.
- Slice the cooked chicken breasts and serve it atop the creamy pasta. Garnish with chopped parsley, if desired.

-----

## Notes

Meal plan (I made a new one with just one recipe so its easier to test)
# Week of February 18th
## Sunday
- [[Chicken Alfredo (4 servings)]]
## Monday
- [[Chicken Alfredo (4 servings)]]
## Tuesday

## Wednesday

## Thursday

## Friday

## Saturday

Linked files below
[Meal Plan.md](https://github.com/tmayoff/obsidian-meals/files/14335669/Meal.Plan.md)
[Chicken Alfredo (4 servings).md](https://github.com/tmayoff/obsidian-meals/files/14335672/Chicken.Alfredo.4.servings.md)

**Comment by tmayoff** [comment]
If you're on desktop could you open the developer console with Ctrl+Shift+i and then try to generate the shopping list, and see if there are any errors you can send me
