### ISSUE TITLE
Support RecipeMD format?

### ISSUE THREAD

**Issue by careilly** [tmayoff/obsidian-meals#33]
Are you interested in supporting the RecipeMD format? https://recipemd.org/

I'm thinking a format switch in preferences and then the ingredients parser can decide which format to use. I've done a quick and dirty implementation but I'd have to clean it up for release …

**Comment by tmayoff** [comment]
I'm for it, I very briefly looked into it and have been wanted to improve the parsing #31 anyways. This seems like a good idea

For later it'd be really good to integrate/make a tool similar to this, https://github.com/AberDerBart/recipemd-extract

**Comment by careilly** [comment]
https://github.com/careilly/obsidian-meals/tree/recipemd￼

This is *awful*, but it mostly works. I’ll tidy it up. 

I suppose ideally it would strip out the quantities for the ingredients list and total them up when making the shopping list.

**Comment by careilly** [comment]
PR issued, hopefully I've done that right. 

It probably is totaling the ingredients, just my ingredients lists are a mess.
