### ISSUE TITLE
Only reload recipes if file in recipes folder is changed

### ISSUE THREAD

**Issue by careilly** [tmayoff/obsidian-meals#45]
Right now it's triggering whenever you modify a file in the vault anywhere, which isn't very efficient, and is pretty noticeable if you have a good number of recipes in a vault.

I think a check on the parent of the file in the ctx of of the modify event would do the job, if there isn't a better way to hook into changes to a specific folder?

**Comment by careilly** [comment]
I think #34 fixes this.

**Comment by tmayoff** [comment]
Fixed #34
