### ISSUE TITLE
Put ingredient description then quantity and unit of measure in Shopping List

### ISSUE THREAD

**Issue by WhyMe4** [tmayoff/obsidian-meals#55]
When I'm shopping, I'd rather see the ingredient name, then the quantity and unit. Would it be possible to add this as an configuration option?

**Comment by tmayoff** [comment]
I'm fine with just changing the order, I never put much thought into the current order.

Maybe at some point an option to configure how things are added e.g "{name} {quantity} {unit}". But that's probably more complicated than necessary.

I'll try to get this done this weekend

**Comment by WhyMe4** [comment]
Thanks. I would do the pull and make the changes, but I've not done any real coding in more years than I can to admit. On Jun 28, 2024, at 10:20 AM, Tyler ***@***.***> wrote: I'm fine with just changing the order, I never put much thought into the current order. Maybe at some point an option to configure how things are added e.g "{name} {quantity} {unit}". But that's probably more complicated than necessary. I'll try to get this done this weekend — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by WhyMe4** [comment]
I tried to update via Obsidian, and it failed. I've also tried removing the plugin and reinstalling, but it also failed. On Jun 28, 2024, at 8:34 PM, Tyler ***@***.***> wrote: Closed #55 as completed via #56 . — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by tmayoff** [comment]
damn I keep doing this, I tried to release it as a beta version to test myself. I'll create the actual release now
