### ISSUE TITLE
Double unit of measures, second one is considered ingredient

### ISSUE THREAD

**Issue by WhyMe4** [tmayoff/obsidian-meals#67]
If the recipe has

- 7 oz (200 g) mushrooms, chopped into small pieces

The shopping list entry will be 
- [ ] (200 g) mushrooms, chopped into small pieces 7 oz 

Would be nice to recognize second unit of measure in () and produce
- [ ] mushrooms, chopped into small pieces 7 oz (200 g)

**Comment by tmayoff** [comment]
So there's a couple of way this can be handled and I'm not currently sure which is the best way. 
(This is just some of my thoughts on it) 

Currently there's an Advanced Ingredient parsing option in the settings which at the moment just ignores things after the first comma, e.g. (`7 oz (200 g) mushrooms, chopped into small pieces`, becomes: `7 oz (200 g) mushrooms`). 

In some of my recipes if have `Zingy Garlic and Oregano Spices (salt, paprika, garlic, vinegar powder, onion, red bell pepper, black pepper, sunflower oil, oregano, parsley, chives, cayenne pepper) 10g` so there can't be any single way to handle brackets in ingredients, other than straight ignoring things inside brackets.

There could be some attempt to parse the bracket contents as quantities and if that fails ignore them.

I'm leaning slightly into maybe ignoring the brackets and potentially provide a way to standardize the ingredients parsing to metric/imperial either in the settings globally or per recipe note, or just a way to format the quantities with (imperial/metric)

**Comment by WhyMe4** [comment]
What if you look for a number value in the ()? Might even be more specific like a number following (. I'm not very good at regex expressions but something like \(\d+[A-z0-9\s]*\). I think this lead to very few false positives for a secondary UoM but still allow expansions like your spice example. On Jul 1, 2024, at 12:27 PM, Tyler ***@***.***> wrote: So there's a couple of way this can be handled and I'm not currently sure which is the best way. (This is just some of my thoughts on it) Currently there's an Advanced Ingredient parsing option in the settings which at the moment just ignores things after the first comma, e.g. ( 7 oz (200 g) mushrooms, chopped into small pieces , becomes: 7 oz (200 g) mushrooms ). In some of my recipes if have Zingy Garlic and Oregano Spices (salt, paprika, garlic, vinegar powder, onion, red bell pepper, black pepper, sunflower oil, oregano, parsley, chives, cayenne pepper) 10g so there can't be any single way to handle brackets in ingredients, other than straight ignoring things inside brackets. There could be some attempt to parse the bracket contents as quantities and if that fails ignore them. I'm leaning slightly into maybe ignoring the brackets and potentially provide a way to standardize the ingredients parsing to metric/imperial either in the settings globally or per recipe note, or just a way to format the quantities with (imperial/metric) — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by tmayoff** [comment]
I'll try to write up some docs, but it'll try to parse the contents of `(...)` and if it succeeds it'll be added as alternate quantities. To have those appear in the shopping list you'll have to modify the `Shopping list format` setting to include them `{description} {quantity} {unitOfMeasure} ({altQuantity} {altUnitOfMeasure})`, an extra post processing step in the formatting will be performed to remove empty `()` before pasting it into the note
